### ISSUE TITLE
Convert.py not displaying expected output

### ISSUE THREAD

**Issue by RidaAyed** [rolfschr/GSWL-ecosystem#4]
Hi

Reading https://rolfschr.github.io/gswl-book/latest.html#Get_data_from_Northbank I expect to see `northbank.tmp.txt` as described
> You should see the data from CSV/apr2042_northbank.csv converted into Ledger's format. The data is stored in ./tmp/northbank.tmp.txt

Now I see
![Screenshot](https://i.imgur.com/Nz2SMHk.png)

Source of message in screenshot https://github.com/rolfschr/GSWL-ecosystem/blob/master/convert.py#L165

**Comment by ravindra1307** [comment]
Which python version and os you are using?

**Comment by RidaAyed** [comment]
Thanks for asking Ravindra:

- Python 3.6
- Arch Linux 4.15

**Comment by ravindra1307** [comment]
can you please provide example of a sample argument to pass to run it . little weak in this accountancy stuffs.

**Comment by RidaAyed** [comment]
The expected view should display --the bank csv rows converted as-- transactions. A transaction looks like this:
```
2015/10/12 Exxon
    Expenses:Auto:Gas         $10.00
    Liabilities:MasterCard   $-10.00
```

**Comment by ravindra1307** [comment]
will you be able to provide me some sample datafiles so that i can test run it

**Comment by ravindra1307** [comment]
sir it will be of great help if you will be able to provide me a sample bankaccount.yml file and csv file

**Comment by RidaAyed** [comment]
@ravindra1307  

Clone this repo: https://github.com/rolfschr/GSWL-private

**Comment by rolfschr** [comment]
Hi,

the code to copy the file to ``./tmp`` is here: https://github.com/rolfschr/GSWL-ecosystem/blob/master/alias#L96,L98
Could it be that there is no ``./tmp`` folder and the tee doesn't work? If so, I guess I need to add a ``mkdir`` to the code. Let me know if this works.

EDIT: updated link

**Comment by RidaAyed** [comment]
@rolfschr thanks for stopping by. The folder exists and running `lmnorthbank` creates `/home/ra/src/GSWL-private/tmp/apr2042_northbank.csv.tmp` and `/home/ra/src/GSWL-private/tmp/apr2042_northbank.csv.tmp.bak` as well if `lmnorthbank` is repeat.  

However the content of both (tmp and tmp.bak) files consists only these 4 lines
```


; Attention: The following lines from ./CSV/apr2042_northbank.csv were ignored:
; 13/04/2042,xxx,xx-xx-xx,xxxxxxxx,Transfer to John Doe Southbank,500.00,,
```

Do you have any other ideas?

**Comment by rolfschr** [comment]
Hi,

the following works perfectly fine for me (I had to change something in the ecosystem but I believe this is completely unrelated).

```
test@tuxpad:~$ mkdir -p ~/src && cd ~/src
test@tuxpad:~/src$ rm -rf GSWL*
test@tuxpad:~/src$ git clone https://github.com/rolfschr/GSWL-ecosystem.git
Cloning into 'GSWL-ecosystem'...
remote: Counting objects: 261, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 261 (delta 0), reused 1 (delta 0), pack-reused 258
Receiving objects: 100% (261/261), 40.30 KiB | 312.00 KiB/s, done.
Resolving deltas: 100% (137/137), done.
test@tuxpad:~/src$ git clone https://github.com/rolfschr/GSWL-private.git
Cloning into 'GSWL-private'...
remote: Counting objects: 167, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 167 (delta 9), reused 9 (delta 9), pack-reused 156
Receiving objects: 100% (167/167), 29.53 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (83/83), done.
test@tuxpad:~/src$ cd ~/src/GSWL-private && source ~/src/GSWL-ecosystem/alias
test@tuxpad:~/src/GSWL-private$ lmnorthbank 
....
test@tuxpad:~/src/GSWL-private$ head tmp/apr2042_northbank.csv.tmp 
2042/04/29 * IdiotsUnlimited
    ; CSV data:
    ; from : 29/04/2042,xxx,xx-xx-xx,xxxxxxxx,IdiotsUnlimited,-1337.00,,
    ; (raw): 29/04/2042,xxx,xx-xx-xx,xxxxxxxx,IdiotsUnlimited,,1337.00,
    Income:Salary:IdiotsUnlimited              $-1337
    Assets:NorthBank:Checking

2042/04/29 * Richard Flatmate
    ; CSV data:
    ; from : 29/04/2042,xxx,xx-xx-xx,xxxxxxxx,Richard Flatmate,-285.50,,
test@tuxpad:~/src/GSWL-private$ 
```

I can't find any issue. I can see in your screenshot that the conversion does not show the transactions in the first place (so it's obvious nothing gets ``tee``'ed to the tmp file). Could you check your setup, possibly starting from scratch?

My test env is
```
test@tuxpad:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
test@tuxpad:~$ echo $BASH_VERSION 
4.4.12(1)-release
test@tuxpad:~$ python --version
Python 2.7.14
```

**Comment by RidaAyed** [comment]
Hi @rolfschr 

Starting from scratch leads to this issue,  

https://github.com/rolfschr/GSWL-book/issues/9#issue-297818546

---

My environment

$ uname -r  
`4.15.3-1-ARCH`

echo $BASH_VERSION  
`4.4.18(1)-release`

$ python --version  
`Python 3.6.4`

---
Could it be the python version?

**Comment by RidaAyed** [comment]
Solved with these steps:

1. $ sudo pacman -S python2-pip
2. $ sudo pip2 install pyyaml
3. Changed line 1 in `convert.py`

from  
```
#!/usr/bin/python
```
to  
```
#!/usr/bin/python2
```

**Comment by rolfschr** [comment]
Fixed py3 issue with 2a5aa19

**Comment by HenricoWitvliet** [comment]
The problem with Python 3 still exists. It can be solved if "a+" on line 142 of convert.py is changed to "r".
Explanation: Python 2 starts reading at the beginning of the file with mode "a+", Python 3 starts reading at the end of the file with mode "a+". fh.seek(0) would also solve the problem.

Unrelated: yaml.load gives a warning with a recent version of pyyaml. This can be solved by adding the argument Loader=yaml.CLoader.

**Comment by rolfschr** [comment]
Thanks for your feedback. I am currently testing py3 implementation of
the scripts and indeed also stumbled over the r vs a+ issue. I will
release py3 once I'm satisfied.
